name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.2.1
        with:
          required-ros-distributions: galactic
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.2.3
        with:
          package-name: gazebo_gridmap_plugin
          import-token: ${{secrets.GITHUB_TOKEN}}
          target-ros2-distro: galactic
          colcon-defaults: |
            {
              "test": {
                "ctest-args": [
                "-LE", "copyright"
                ]
              }
            }

